services:
  # Admin Service (Vite + ReactJS)
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  # Front-End Service (Create React App)
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  # Back-End Service (ExpressJS)
  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
